name: Self hosted runner
on:
  push:
    runs-on: [istanbul-kubo]
    branches: [ githubCI, playwright, develop, main ]
  pull_request:
    branches: [ githubCI, playwright, develop, main ]
    runs-on: [istanbul-kubo]

jobs:
  build:
    timeout-minutes: 60
    runs-on: deContact
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
      actions: read
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} 
    env:
      VITE_SEED_NODES:  ${{ secrets.VITE_SEED_NODES }} 
      VITE_P2P_PUPSUB: ${{ secrets.VITE_P2P_PUPSUB }} 
      PAGE_URL: ${{ secrets.PAGE_URL }} 
      SEED_TEST: ${{ secrets.SEED_TEST }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 21  
    - name: Install dependencies
      run: |
        npm install
        npm run build:fixed      
        sed -i 's|/service-worker.js|./service-worker.js|g' build/index.html    
        sed -i 's|"/"|"./deContact/"|g' build/_app/immutable/entry/app.*.js
        sed -i 's|/_app/version.json|./_app/version.json|g' build/_app/immutable/chunks/entry.*.js
    - uses: actions/upload-pages-artifact@v3 
      with:
        path: ./build
    - uses: actions/deploy-pages@v4
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps  
    #- name: Start test BasicAddressExchange.spec.js
    #  run: npx playwright test BasicAddressExchange.spec.js
    - name: Start test MyDevicesAutoSync.spec.js 
      run: npx playwright test MyDevicesAutoSync.spec.js 
